export const GET_CITIES = 'GET_CITIES';
export const SEARCH_CITIES ='SEARCH_CITIES';
export const GET_ITINERARIES = 'GET_ITINERARIES';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const POST_USER_DATA = 'POST_USER_DATA';
export const LOGIN_USER = 'LOGIN_USER';